AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM 111template for deploying Lambda functions.

Resources:
# Details about Lambda1 function
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      FunctionName: indexphotos
      Role: arn:aws:iam::764420359320:role/assign2
      CodeUri: s3://assignment2.b3-code-repo/lambda/SourceArti/lf1
      Timeout: 30




